[funk_sftp]
type = sftp
user = root
port = 9000
use_agent_auth = true
skip_hostkey_check = true
# These next lines stop the "Can't save config" errors
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
