services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil:v1
    environment:
      # For write permission in config directory
      - PUID=1000
      - PGID=1000
    volumes:
      - $SWITCH_PATH:/games
      - $DOCKER_CONFIG_PATH/ownfoil:/app/config
    ports:
      - "8001:80"
    labels:
      com.centurylinklabs.watchtower.enable: true

  rsync-server:
    image: quentintin/rsync-server
    container_name: rsync-server
    volumes:
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/authorized_keys
      - $PICTURES_PATH/Pictures:/data/Pictures:ro
      - $MUSIC_ROOT_PATH:/data/music:ro
    environment:
      #- USERNAME=nouser
      #- PASSWORD=nopass
      PUID: $PUID_USER
      PGID: $PGID_USER
    ports:
      #- "873:873" #uncomment if want to use rsyncd
      - "9000:22"
    restart: always


  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: $TZ
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $PICTURES_PATH:/share5
    command: |
      -s "Pictures;/share5;yes;no;no;$USER;$USER;$USER;pictures ro except user"
      -u "guest;guest"
      -u "$USER;$SAMBA_PASSWORD"
      -g "map to guest = Bad User"
      -g "guest account = nobody"
  homer:
    image: b4bz/homer:latest
    container_name: homer
    environment:
      # - PUID=$PUID_USER
      # - PGID=$PGID_USER
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
    volumes:
      - $DOCKER_CONFIG_PATH/homer/config.yml:/www/config.yml
      - $DOCKER_CONFIG_PATH/homer/local/assets/:/www/assets
    ports:
      - 80:8080
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      #traefik.enable: true
      #traefik.http.routers.home.rule: Host(`home.brownfunk.lan`)
      #traefik.http.routers.home.entrypoints: web
      #traefik.http.services.home.loadbalancer.server.port: 80
#
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=$PUID_USER
      - PGID=$PGID_USER
      - TZ=$TZ
      - FB_NOAUTH=True
      - FB_BASEURL=/filebrowser
      - FB_DATABASE=/config/filebrowser.db
      - WATCHTOWER_CLEANUP=true
    ports:
      - 9295:80
    volumes:
      - $DOCKER_CONFIG_PATH/filebrowser/database:/database
      - $DOCKER_CONFIG_PATH/filebrowser/config:/config
      - $EBOOKS_AUDIOBOOKS_PATH:/srv/ebooks_audiobooks:ro
      - $MUSIC_PATH:/srv/music:ro
      # - $MOVIES_PATH:/srv/movies:ro
      # - $TORRENT_PATH:/srv/torrent:ro
      - $SELF_IMPROVEMENT_PATH:/srv/self_improvement:ro
      - $GAMES_PATH:/srv/games:ro
      - $SHARE_PATH:/srv/share
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true

  navidrome:
    image: deluan/navidrome
    container_name: navidrome
    user: $PUID_USER:$PGID_USER # should be owner of volumes
    ports:
      - "8082:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANINTERVAL: 8h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_AUTOIMPORTPLAYLISTS: "true"
      ND_RECENTLYADDEDBYMODTIME: "true"
      ND_LASTFM_APIKEY: $LASTFM_API
      ND_LASTFM_SECRET: $LASTFM_SECRET
      ND_SPOTIFY_ID: $SPOTIFY_ID
      ND_SPOTIFY_SECRET: $SPOTIFY_SECRET
      ND_ENABLETRANSCODINGCONFIG: "true"
      ND_ENABLEGRAVATAR: "true"
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - $DOCKER_CONFIG_PATH/navidrome:/data
      - $MUSIC_PATH:/music:ro
    labels:
      com.centurylinklabs.watchtower.enable: true
#


  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_LABEL_ENABLE: 1
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --interval 3600
    labels:
      com.centurylinklabs.watchtower.enable: true
#
volumes:
  netdatalib:
  netdatacache:
  photoprism-originals:
    driver: local
    driver_opts:
      type: cifs
      o: "username=$SAMBA_PICTURES_USER,password=$SAMBA_PICTURES_PASSWORD,rw"
      device: "//$SERVER_URL/pictures"

