---
# Homepage configuration
title: "Beefunk"
header: False
footer: '<p>Created with <span class="has-text-danger">❤️</span>. Click on  <a href="http://beefunk:3000/s/H1tA_LShH" target="_.local">Server How to</a> to understand how to get by.</i></a></p>'
connectivityCheck: true
theme: dark
colors:
  dark:
    highlight-primary: "#2b2b2b"
    highlight-secondary: "#484d54"
    highlight-hover: "#cfdfae"
    background: "#1313134a"
    card-background: "#2b2b2b"
    text: "#cadfae"
    text-header: "#cfdfae"
    text-title: "#cfdfae"
    text-subtitle: "#cfdfae"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#cfdfae"
  light:
    highlight-primary: "#2b2b2b"
    highlight-secondary: "#484d54"
    highlight-hover: "#cfdfae"
    background: "#1313134a"
    card-background: "#2b2b2b"
    text: "#cadfae"
    text-header: "#cfdfae"
    text-title: "#cfdfae"
    text-subtitle: "#cfdfae"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#cfdfae"

message:
  style: "is-warning"
  title: "Welcome to Beefunk!!"
  content: '<a href="http://home.beefunk.local">http://home.beefunk.local</a> <br> Find more information about this media server at <a href="http://beefunk:3000/s/H1tA_LShH" target="_.local">Server How to</a>'

links:
  - name: "Server Howto"
    icon: "fas fa-book"
    url: "http://beefunk:3000/s/H1tA_LShH"
    target: "_.local"

services:
  - name: "Daily & Productivity"
    icon: "fas fa-star"
    items:
      - name: "Mealie"
        logo: "https://avatars.githubusercontent.com/u/92342333?s=48&v=4"
        subtitle: "Mealie - Recipes & meal planning"
        url: "http://mealie.beefunk.local"
        target: "_.local"
        tag: "app"

      - name: "LingoDiary"
        logo: "http://lingodiary.beefunk.local/static/icon_reduced.png"
        subtitle: "LingoDiary - language learning"
        tag: "app"
        url: "http://lingodiary.beefunk.local"
        target: "_.local"

      - name: "Blog - El Camino Loco"
        logo: "assets/wordpress.png"
        subtitle: "Wordpress - El Camino Loco"
        tag: "loz"
        url: "http://beefunk:5555"
        target: "_.local"

      - name: "Music Sheet"
        logo: "assets/solfege.png"
        subtitle: "A list of sheet played throughout years"
        tag: "cloud"
        url: "http://brownfunk.local:3000/s/BW3Tx522S#"
        target: "_.local"

  - name: "Media Streaming"
    icon: "fas fa-film"
    items:
      - name: "Movies"
        logo: "assets/jellyfin.png"
        subtitle: "Jellyfin - media streaming"
        tag: "app"
        tagstyle: "is-success"
        url: "http://jellyfin.beefunk.local"
        target: "_.local"

      - name: "Audiobooks"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/audiobookshelf.png"
        subtitle: "AudiobookShelf - Audiobook streaming"
        tag: "app"
        tagstyle: "is-success"
        url: "http://audiobookshelf.beefunk.local"
        target: "_.local"

      - name: "Music"
        logo: "assets/navidrome.png"
        subtitle: "Navidrome - music streaming"
        tag: "app"
        url: "http://navidrome.beefunk.local"
        target: "_.local"

      - name: "Music - myMPD"
        logo: "https://avatars.githubusercontent.com/u/765844?v=4"
        subtitle: "myMPD MPD client - music"
        tag: "app"
        url: "http://mympd.beefunk.local"
        target: "_.local"

      - name: "Music - Moode"
        logo: "https://moodeaudio.org/forum/images/moode-r900-logotype-175px.png"
        subtitle: "MPD Moode Server"
        tag: "app"
        url: "http://moode.local"
        target: "_.local"

      - name: "Comics"
        logo: "assets/komga.png"
        subtitle: "Komga - Comics streaming"
        tag: "app"
        tagstyle: "is-success"
        url: "http://komga.beefunk.local"
        target: "_.local"

      - name: "Ebooks"
        logo: "assets/calibre.png"
        subtitle: "Calibre Web - Ebooks download"
        tag: "app"
        tagstyle: "is-success"
        url: "http://calibre-web.beefunk.local"
        target: "_.local"

  - name: "Photos & Gallery"
    icon: "fas fa-images"
    items:
      - name: "Immich"
        logo: "https://user-images.githubusercontent.com/27055614/182044984-2ee6d1ed-c4a7-4331-8a4b-64fcde77fe1f.png"
        subtitle: "Immich - pictures"
        tag: "app"
        url: "http://immich.beefunk.local"
        target: "_.local"

      - name: "Pictures"
        logo: "assets/lens.png"
        subtitle: "Piwigo - Picture gallery"
        tag: "loz"
        url: "http://piwigo.beefunk.local"
        target: "_.local"

      - name: "Photoprism"
        logo: "assets/photoprism.png"
        subtitle: "Photoprism - Picture gallery"
        tag: "loz"
        url: "http://beefunk:2342"
        target: "_.local"

  - name: "Gaming & Emulation"
    icon: "fas fa-gamepad"
    items:
      - name: "Romm"
        logo: "http://romm.beefunk.local/assets/isotipo.svg"
        subtitle: "Romm - ROM manager"
        tag: "app"
        tagstyle: "is-success"
        url: "http://romm.beefunk.local"
        target: "_.local"

      - name: "Aerofoil"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nintendo-switch.svg"
        subtitle: "Aerofoil - switch games"
        tag: "app"
        tagstyle: "is-success"
        url: "http://aerofoil.beefunk.local"
        target: "_.local"

  - name: "Cloud & Sync"
    icon: "fas fa-cloud"
    items:
      - name: "Cloud storage"
        logo: "assets/nextcloud.png"
        subtitle: "Nextcloud - cloud storage"
        tag: "cloud"
        url: "https://brownfunk.local:9393"
        target: "_.local"

      - name: "Syncthing"
        logo: "assets/syncthing.ico"
        subtitle: "Sync data between devices"
        tag: "cloud"
        url: "https://syncthing.beefunk.local"
        target: "_.local"

      - name: "File Browser"
        logo: "assets/quantum.png"
        subtitle: "Filebrowser - explore and download files on server"
        tag: "app"
        tagstyle: "is-success"
        url: "http://filebrowserquantum.beefunk.local"
        target: "_.local"

  - name: "Downloads & Indexers"
    icon: "fas fa-download"
    items:
      - name: "Torrent"
        logo: "assets/transmission.png"
        subtitle: "Transmission + VPN - torrent download"
        tag: "dl"
        url: "http://transmission.beefunk.local"
        target: "_.local"

      - name: "Prowlarr"
        logo: "http://prowlarr.beefunk.local/Content/Images/logo.png"
        subtitle: "Prowlarr - Search torrent"
        tag: "dl"
        url: "http://prowlarr.beefunk.local"
        target: "_.local"

      - name: "Jackett"
        logo: "assets/jackett.png"
        subtitle: "Jackett - torrent proxy"
        tag: "dl"
        url: "http://jackett.beefunk.local"
        target: "_.local"

      - name: "Movie Download"
        logo: "assets/radarr.png"
        subtitle: "Radarr - movie download"
        tag: "dl"
        url: "http://radarr.beefunk.local"
        target: "_.local"

      - name: "Movie (French) Download"
        logo: "assets/radarr.png"
        subtitle: "Radarr - french movie download"
        tag: "dl"
        url: "http://brownfunk.local:7879"
        target: "_.local"

      - name: "TV show Download"
        logo: "assets/sonarr.png"
        subtitle: "Sonarr - movie download"
        tag: "dl"
        url: "http://sonarr.beefunk.local"
        target: "_.local"

      - name: "Music Download"
        logo: "assets/lidarr.svg"
        subtitle: "Lidarr - music download"
        tag: "dl"
        url: "http://lidarr.brownfunk.local"
        target: "_.local"

      - name: "Subtitle Download"
        logo: "assets/bazarr.png"
        subtitle: "Bazarr - subtitle download"
        tag: "dl"
        url: "http://brownfunk.local:6768"
        target: "_.local"

      - name: "Downloader"
        logo: "assets/pyload.png"
        subtitle: "Pyload - download any link to server"
        tag: "dl"
        url: "http://brownfunk.local:8000"
        target: "_.local"

  - name: "Server Maintenance & Tools"
    icon: "fas fa-tools"
    items:
      - name: "Portainer"
        logo: "assets/portainer.png"
        subtitle: "Portainer - docker images"
        url: "http://portainer.beefunk.local"
        tag: "geek"
        target: "_.local"

      - name: "Cockpit"
        logo: "assets/cockpit.png"
        subtitle: "Debian console - VM"
        tag: "geek"
        url: "https://beefunk.local:9090"
        target: "_.local"

      - name: "Pi Hole"
        logo: "assets/pihole.png"
        subtitle: "Pi Hole - adblocker DNS & DHCP server"
        tag: "geek"
        url: "http://pihole.beefunk.local/admin"
        target: "_.local"

      - name: "Router"
        logo: "assets/asusrouter.png"
        subtitle: "Router config"
        tag: "geek"
        url: "http://192.168.1.1"
        target: "_.local"

      - name: "Scrunity"
        logo: "https://raw.githubusercontent.com/AnalogJ/scrutiny/master/webapp/frontend/src/assets/images/logo/scrutiny-logo-dark.png"
        subtitle: "Monitor HDD - realtime"
        tag: "geek"
        url: "http://beefunk:8033"
        target: "_.local"

      - name: "Grafana"
        logo: "assets/grafana.png"
        subtitle: "Grafana monitoring - admin(secret)"
        tag: "geek"
        url: "http://beefunk:3005"
        target: "_.local"

      - name: "Ebooks"
        logo: "assets/calibre.png"
        subtitle: "Calibre Server - Ebooks Maintenance"
        tag: "app"
        tagstyle: "is-success"
        url: "http://beefunk:8081"
        target: "_.local"

      - name: "Unmanic"
        logo: "http://unmanic.beefunk.local/unmanic/img/unmanic-logo-white.a3277864.png"
        subtitle: "Unmanic - Convert videos automatically"
        tag: "app"
        tagstyle: "is-success"
        url: "http://unmanic.beefunk.local"
        target: "_.local"

      - name: "Firefox"
        logo: "assets/firefox.png"
        subtitle: "Firefox"
        tag: "dl"
        url: "https://beefunk:3009"
        target: "_.local"
